name = "simplebskylabeler"
main = "src/index.ts"
preview_urls = false
workers_dev = false
send_metrics = false
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./html"
binding = "ASSETS"
html_handling = "drop-trailing-slash"
run_worker_first = ["/", "!/img", "!/css", "!/js", "!/favicon.ico", "/site.webmanifest", "!/robots.txt"]

# You can modify all settings past this comment
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "bskylabels"
database_id = ""

[vars]
COUNT_CACHE_HOUR="4"
# Site metadata
SITE_TITLE="Simple BSky Labeler"
SITE_DESCRIPTION="Allow people to obtain a bsky label you provide"
# this is used for the site.webmanifest
SITE_SHORTNAME="SBL"

# bsky information

# This should be your account DID string
LABEL_SRC=""
# this should be the short name of the label
LABEL_VAL=""
